name: dashmonx
description: A CLI tool to run Flutter applications with automatic hot reload on file changes
version: 1.0.1
homepage: https://github.com/rosenpin/dashmonx

executables:
  dashmonx:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  watcher: ^1.1.1

dev_dependencies:
